database:
  type: SYNCMAN_DB_TYPE
  name: SYNCMAN_DB_NAME
  host: SYNCMAN_DB_HOST
  username: SYNCMAC_DB_USERNAME
  password: SYNCMAN_DB_PASSWORD
  timezone: US/Eastern

tables:
  agent:
    name: sync_agent
    agent: agent
    created: created_on
  claim:
    name: sync_claim
    agent: agent
    claim: claim
  audit:
    name: sync_audit
    created: created_on
    agent: agent
    claim: claim
    date: date
